**Theoretical** **Questions**

In [ ]:
#  1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
'''
(Ans)
NumPy is a powerful tool in Python that makes working with numbers and large sets of data easier and faster, which is why it’s so popular in fields
like data analysis, scientific computing, and machine learning.

NumPy is mainly designed to handle large amounts of numbers efficiently. It provides a special data structure called an "array" that is more
powerful than regular Python lists when it comes to numerical calculations. This array structure allows us to perform complex mathematical operations
much faster, which is critical in fields where you need to process and analyze big datasets or perform lots of calculations, like scientific research or AI.

Why Use NumPy?
Here are some of the biggest reasons:

1.Speed and Efficiency
   NumPy arrays are designed to be faster and use memory more efficiently than Python’s standard lists. This is because they store data in a way that’s
   very easy for the computer to access, making operations on big datasets much quicker.

2. Easier Math with Vectorized Operations
   NumPy lets you do mathematical operations on entire arrays at once without writing loops. So, instead of having to multiply each item in a list by a number one at a time,
   you can just tell NumPy to multiply the whole array, and it does it in a single step. This saves time and makes the code cleaner and faster.

3. Wide Range of Built-in Math Functions
   NumPy includes a huge variety of math functions, from basic operations like addition and subtraction to more complex ones like trigonometry and statistics.
   These functions are designed to be as fast and accurate as possible, making calculations easier and more reliable.

4. Works Well with Other Python Libraries
   NumPy is compatible with many other popular libraries, like Pandas for data manipulation and Matplotlib for creating visualizations.
   Many machine learning libraries, like TensorFlow, also rely on NumPy, so knowing it makes using these other tools much easier.

5. Multi-dimensional Arrays
   While regular Python lists are limited, NumPy arrays can handle multiple dimensions, which is essential for data like images or multi-layered tables.
   This flexibility allows you to work with data in a way that better reflects its actual structure.

6. Broadcasting Simplifies Calculations
   With broadcasting, you can perform operations on arrays of different shapes without writing complex code. For example, you can add a 1D array to each row
   of a 2D array in one step, which is especially helpful in scientific computing.

7. Integration with C and C++ for Extra Speed
   NumPy is built on C, which is a very fast language, and you can connect it to code written in C or C++ for even more speed when working with huge datasets.

Python is great for writing readable code, but it’s not the fastest for math-heavy operations on big datasets. NumPy speeds this up by providing a high-performance
way to handle numbers and arrays. It turns Python into a language that can compete with traditional scientific computing tools, making it a strong choice for data analysis,
machine learning, and complex scientific calculations.

'''

In [ ]:
# 2.  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
'''
(Ans)
np.mean() and np.average() are both functions in NumPy used to calculate the mean of an array,

Here’s a comparison of the two and when we might choose one over the other.

1. Basic Difference in Functionality
np.mean(): This function calculates the arithmetic mean (simple average) of the values in an array along the specified axis.
It treats all elements equally and does not accept weights.
np.average(): This function can also calculate the mean, but it allows you to assign weights to each element in the array.
By providing a weights parameter, you can calculate a weighted average, which gives different importance to different values.
2. Syntax
np.mean(): np.mean(array, axis=None)
np.average(): np.average(array, axis=None, weights=None)
If you don’t specify weights in np.average(), it functions exactly like np.mean() and simply calculates the arithmetic mean.

3. Weighted Mean (Only in np.average())
Example of Weighted Average with np.average(): Suppose you have an array of scores [10, 20, 30] and want to calculate the weighted average with weights
[1, 2, 3]. Using np.average() with weights, you get:


np.average([10, 20, 30], weights=[1, 2, 3])
This means the value 30 is given three times the importance of 10.

No Weighting in np.mean(): np.mean() treats all values equally, so if you need a weighted result, only np.average() can provide it.

4. Handling NaN Values
Both np.mean() and np.average() don’t handle NaN values automatically, but you can use np.nanmean() if you want to ignore NaN values in your calculations
(no equivalent exists for np.average()).
When to Use Each Function
Use np.mean() when:

You want a simple, straightforward average where all values are treated equally.
You don’t need to apply any weights.
You want cleaner syntax for calculating the mean of an array without additional parameters.
Use np.average() when:

You need a weighted average where certain values should have more influence on the result than others.
You want flexibility in giving different values more or less importanc
'''

In [2]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays?
'''
(Ans)
To reverse a NumPy array, you can use slicing with negative indices or functions like np.flip().
Reversing along different axes is possible by specifying the axis.
Example
# 1D Array
arr_1d = np.array([1, 2, 3, 4])
reversed_1d = arr_1d[::-1]
Output: [4 3 2 1]

# 2D Array
arr_2d = np.array([[1, 2], [3, 4]])
reversed_2d = np.flip(arr_2d, axis=0)
Output: [[3 4]
         [1 2]]

'''

'\n(Ans)\nTo reverse a NumPy array, you can use slicing with negative indices or functions like np.flip().\nReversing along different axes is possible by specifying the axis.\n# 1D Array\narr_1d = np.array([1, 2, 3, 4])\nreversed_1d = arr_1d[::-1]\n\n# 2D Array\narr_2d = np.array([[1, 2], [3, 4]])\nreversed_2d = np.flip(arr_2d, axis=0)\n\n'

In [3]:
# 4.  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

'''
(Ans)
The data type of elements in a NumPy array can be determined using the dtype attribute.

Importance of Data Types:
Data types help in memory optimization and ensure efficient computation. Choosing an appropriate data type
can reduce memory usage and improve performance in large datasets.

Example:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype
Output: int32
'''

'\n(Ans)\nThe data type of elements in a NumPy array can be determined using the dtype attribute.\n\nImportance of Data Types:\nData types help in memory optimization and ensure efficient computation. Choosing an appropriate data type\ncan reduce memory usage and improve performance in large datasets.\n\nExample:\narr = np.array([1, 2, 3], dtype=np.int32)\narr.dtype\nOutput: int32\n'

In [ ]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''
(Ans)
Definition of ndarrays:
An ndarray is a multi-dimensional array in NumPy for efficient storage and manipulation of large data sets.

Key Features:

Homogeneous: All elements have the same data type.
Fixed Size: Array size is fixed once created.
Supports Mathematical Operations: Fast, vectorized operations without explicit loops.
Difference from Python Lists:
Python lists are general-purpose, while ndarrays are specialized for numerical data, allowing more efficient memory usage and faster computation.

 '''

In [ ]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.?
'''
(Ans)
Performance Benefits of NumPy Arrays:
NumPy arrays are faster and more memory-efficient than Python lists for large-scale numerical operations because they:

Avoid type checking overhead by enforcing a single data type.
Use contiguous memory blocks, resulting in faster access and processing.
Allow vectorized operations, which are significantly faster than loops.

Example:
'''

In [5]:
import time
import numpy as np
# Python List
lst = list(range(1000000))
start = time.time()
sum_lst = sum(lst)
end = time.time()
list_time = end - start

# NumPy Array
arr = np.array(lst)
start = time.time()
sum_arr = np.sum(arr)
end = time.time()
numpy_time = end - start

list_time, numpy_time

(0.008851289749145508, 0.005782604217529297)

In [6]:
# 7.  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.?
'''
(Ans)
vstack(): Stacks arrays vertically (row-wise).
hstack(): Stacks arrays horizontally (column-wise).
Example
a = np.array([1, 2])
b = np.array([3, 4])
v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))
output
v_stacked:
[[1 2]
 [3 4]]

h_stacked:
[1 2 3 4]
'''

'\n(Ans)\nvstack(): Stacks arrays vertically (row-wise).\nhstack(): Stacks arrays horizontally (column-wise).\nExample\na = np.array([1, 2])\nb = np.array([3, 4])\nv_stacked = np.vstack((a, b))\nh_stacked = np.hstack((a, b))\noutput\nv_stacked:\n[[1 2]\n [3 4]]\n\nh_stacked:\n[1 2 3 4]\n'

In [7]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.?
'''
(Ans)
fliplr(): Flips the array in the left/right direction.
flipud(): Flips the array in the up/down direction.
Example
arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_lr = np.fliplr(arr)
flipped_ud = np.flipud(arr)
Output:
flipped_lr:
[[3 2 1]
 [6 5 4]]

flipped_ud:
[[4 5 6]
 [1 2 3]]
'''

'\n(Ans)\nfliplr(): Flips the array in the left/right direction.\nflipud(): Flips the array in the up/down direction.\nExample\narr = np.array([[1, 2, 3], [4, 5, 6]])\nflipped_lr = np.fliplr(arr)\nflipped_ud = np.flipud(arr)\nOutput:\nflipped_lr:\n[[3 2 1]\n [6 5 4]]\n\nflipped_ud:\n[[4 5 6]\n [1 2 3]]\n'

In [8]:
# 9.  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''
(Ans)
array_split(): Splits an array into multiple sub-arrays.
Example
arr = np.array([1, 2, 3, 4, 5, 6])
splitted = np.array_split(arr, 3)
Output:
splitted:
[array([1, 2]), array([3, 4]), array([5, 6])]

'''

'\n(Ans)\narray_split(): Splits an array into multiple sub-arrays.\nExample\narr = np.array([1, 2, 3, 4, 5, 6])\nsplitted = np.array_split(arr, 3)\nOutput:\nsplitted:\n[array([1, 2]), array([3, 4]), array([5, 6])]\n\n'

In [ ]:
# 10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''
(Ans)
Vectorization: Enables element-wise operations on entire arrays without explicit loops, improving performance.
Broadcasting: Allows arrays of different shapes to be used together in operations, automatically expanding smaller arrays.
Example:
a = np.array([1, 2, 3])
b = np.array([1])
result = a + b

'''

**Practical Questions:**

In [10]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100, then interchange its rows and columns.
import numpy as np
arr = np.random.randint(1, 101, (3, 3))
transposed_arr = arr.T
arr, transposed_arr


(array([[42, 39, 11],
        [88, 68, 45],
        [40, 91, 21]]),
 array([[42, 88, 40],
        [39, 68, 91],
        [11, 45, 21]]))

In [11]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

arr_1d = np.arange(10)
arr_2x5 = arr_1d.reshape(2, 5)
arr_5x2 = arr_1d.reshape(5, 2)
arr_2x5, arr_5x2

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [13]:
# 3. Create a 4x4 NumPy array with random float values and add a border of zeros to make it 6x6.

arr_4x4 = np.random.rand(4, 4)
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
arr_4x4, arr_6x6

(array([[0.29625211, 0.31808439, 0.08885123, 0.34078709],
        [0.31049725, 0.52103051, 0.5726421 , 0.09459451],
        [0.32235847, 0.63879638, 0.64273862, 0.90438839],
        [0.60961798, 0.93140242, 0.5579586 , 0.57129456]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.29625211, 0.31808439, 0.08885123, 0.34078709,
         0.        ],
        [0.        , 0.31049725, 0.52103051, 0.5726421 , 0.09459451,
         0.        ],
        [0.        , 0.32235847, 0.63879638, 0.64273862, 0.90438839,
         0.        ],
        [0.        , 0.60961798, 0.93140242, 0.5579586 , 0.57129456,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

In [14]:
# 4. Create an array of integers from 10 to 60 with a step of 5.

arr = np.arange(10, 61, 5)

arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [15]:
#5. Create an array of strings and apply different case transformations.

arr = np.array(['python', 'numpy', 'pandas'])

upper_case = np.char.upper(arr)
lower_case = np.char.lower(arr)
title_case = np.char.title(arr)

upper_case, lower_case, title_case

(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [16]:
# 6. Insert a space between each character of every word in an array of words.

arr = np.array(['hello', 'world', 'numpy'])

spaced_arr = np.char.join(" ", arr)

spaced_arr

array(['h e l l o', 'w o r l d', 'n u m p y'], dtype='<U9')

In [17]:
# 7. Perform element-wise operations on two 2D NumPy arrays.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition, subtraction, multiplication, and division
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

addition, subtraction, multiplication, division

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [18]:
# 8. Create a 5x5 identity matrix and extract its diagonal elements.

identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

identity_matrix, diagonal_elements

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

In [19]:
# 9. Find and display all prime numbers in an array of 100 random integers between 0 and 1000.?

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True
arr = np.random.randint(0, 1000, 100)

prime_numbers = arr[np.vectorize(is_prime)(arr)]

prime_numbers

array([101, 521, 797,  67, 509, 281, 149])

In [21]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages?

# Pad the array to 35 elements (5 full weeks)
temperatures = np.random.randint(20, 40, 30)
padded_temperatures = np.pad(temperatures, (0, 5), 'constant', constant_values=temperatures.mean())
weekly_temps = padded_temperatures.reshape(5, 7)
weekly_averages = weekly_temps.mean(axis=1)

weekly_averages


array([30.        , 30.85714286, 26.28571429, 32.14285714, 29.14285714])